### ISSUE TITLE
UI Translation possible

### ISSUE THREAD

**Issue by wilzbach** [dlang-tour/annouce#3]
Hi, @dlang-tour/chinese, @dlang-tour/english, @dlang-tour/french, @dlang-tour/german, @dlang-tour/italian, @dlang-tour/japanese, @dlang-tour/korean, @dlang-tour/portuguese, @dlang-tour/romanian, @dlang-tour/russian, @dlang-tour/slovak, @dlang-tour/spanish, @dlang-tour/swedish, @dlang-tour/turkish, @dlang-tour/ukrainian

Updates
-------------

### Finally you can translate the UI buttons

For details, please see https://github.com/dlang-tour/core/pull/510
For an example: https://github.com/dlang-tour/german/pull/61 ([live in action](https://tour.dlang.org/tour/de/welcome/welcome-to-d)).
In short it boils down to adding this to your main `index.yml`

```yaml
translations:
 editor.run: Run
 editor.reset: Reset
 editor.format: Format
 editor.keyboard_shortcuts: Keyboard Shortcuts
 editor.export": Export
```

(You will need `dlang-tour` >= 1.0.6 to test this locally)

### Auto-deploy is working again :tada: 

It turned out to be an issue with ldc-1.2.0. Luckily ldc-1.3.0-beta.2 solved the problem.

### Small things

- there's now a "Format" & "Export" button ([run.dlang.io](https://run.dlang.io/) is rather simplistic atm, PRs are welcome)
- the Tour backend is now used to execute the unittest examples on dlang.org (this heavily reduced the execution time)

As always: happy translating and feel free to open issues at https://github.com/dlang-tour/core/issues :)
